name: run-docker
on:
  push:
    branches: [ main ]
  workflow_dispatch:
env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  build-tag-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: edit the dummy text file
        run: echo "This is a pr" >> dummy.txt
      - name: checkout a branch
        run: git checkout -b test
      - name: create a pr using the github cli
        run: git config user.email "${GH_USERNAME}@users.noreply.github.com" && git config --global user.name ${{ github.actor }} && git add . && git commit -m "test" && gh pr create --title "This is a dummy pr" --body "PR is working"