name: run-docker
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build-tag-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: run gh
        run: gh